Repository feeddeck/feeddeck, pull requests merged in 2025-04, with the labels that each got.

#242 Update Deno Version to 1.45.2
  supabase/functions/_cmd/Dockerfile
  supabase/functions/_cmd/cmd.ts
  supabase/functions/_cmd/scheduler/scheduler.ts
  supabase/functions/_cmd/worker/worker.ts
  supabase/functions/_shared/feed/utils/getAndParseFeed.ts
  supabase/functions/_shared/feed/utils/uploadFile.ts
  supabase/functions/add-or-update-source-v1/index.ts
  supabase/functions/add-source-v1/index.ts
  supabase/functions/delete-user-v1/index.ts
  supabase/functions/generate-magic-link-v1/index.ts
  supabase/functions/import_map.json
  supabase/functions/profile-v1/index.ts
  supabase/functions/profile-v2/index.ts
  supabase/functions/revenuecat-webhooks-v1/index.ts
  supabase/functions/stripe-create-billing-portal-link-v1/index.ts
  supabase/functions/stripe-create-checkout-session-v1/index.ts
  supabase/functions/stripe-webhooks-v1/index.ts
Labels: changelog: changed

#243 Prefer `content` over `description` for Item Description
  supabase/functions/_shared/feed/rss.ts
  supabase/functions/_shared/feed/rss_test.ts
Labels: changelog: changed

#244 Fix Flutter Deprecations
  app/lib/widgets/deck/deck_layout_small.dart
  app/lib/widgets/item/details/utils/item_audio_palyer/item_audio_player_init/item_audio_player_init.dart
  app/lib/widgets/item/details/utils/item_piped/item_piped_video.dart
  app/lib/widgets/item/details/utils/item_piped/item_piped_video_web.dart
  app/lib/widgets/item/details/utils/item_youtube/item_youtube_video.dart
  app/lib/widgets/item/details/utils/item_youtube/item_youtube_video_web.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: changelog: changed

#245 Allow Re-Ordering of Sources in a Column
  app/lib/repositories/app_repository.dart
  app/lib/widgets/column/header/column_layout_header_settings_sources.dart
  app/lib/widgets/source/source_list_item.dart
  supabase/migrations/20250419122600_add_postion_field_to_sources.sql
Labels: changelog: added

#246 Allow Swiping Gestures to Switch Column
  app/lib/widgets/deck/deck_layout_small.dart
Labels: changelog: added

#248 Add Self-Hosting Setup
  CONTRIBUTING.md
  app/.dockerignore
  app/Dockerfile
  supabase/functions/_cmd/docker-compose.yaml
  supabase/hosting/.env.example
  supabase/hosting/.gitignore
  supabase/hosting/README.md
  supabase/hosting/docker-compose.yaml
  supabase/hosting/volumes/api/kong.yml
  supabase/hosting/volumes/db/_supabase.sql
  supabase/hosting/volumes/db/jwt.sql
  supabase/hosting/volumes/db/logs.sql
  supabase/hosting/volumes/db/pooler.sql
  supabase/hosting/volumes/db/realtime.sql
  supabase/hosting/volumes/db/roles.sql
  supabase/hosting/volumes/db/webhooks.sql
  supabase/hosting/volumes/functions/main/index.ts
  supabase/hosting/volumes/logs/vector.yml
  supabase/hosting/volumes/pooler/pooler.exs
Labels: changelog: added

#249 [youtube] Fix Video Playback
  app/lib/widgets/item/details/utils/item_videos.dart
  app/lib/widgets/item/details/utils/item_youtube/item_youtube_video_native.dart
Labels: changelog: fixed

#251 Allow Importing / Exporting of Decks
  app/android/.gitignore
  app/android/app/build.gradle
  app/ios/Podfile
  app/ios/Podfile.lock
  app/ios/Runner/Info.plist
  app/lib/models/column.dart
  app/lib/models/source.dart
  app/lib/models/sources/github.dart
  app/lib/models/sources/googlenews.dart
  app/lib/models/sources/stackoverflow.dart
  app/lib/repositories/app_repository.dart
  app/lib/widgets/item/details/utils/item_piped/item_piped_video_web.dart
  app/lib/widgets/item/details/utils/item_youtube/item_youtube_video_web.dart
  app/lib/widgets/settings/app_settings/app_settings.dart
  app/lib/widgets/settings/app_settings/app_settings_export.dart
  app/lib/widgets/settings/app_settings/app_settings_import.dart
  app/lib/widgets/settings/settings.dart
  app/macos/Flutter/GeneratedPluginRegistrant.swift
  app/macos/Podfile.lock
  app/macos/Runner/DebugProfile.entitlements
  app/macos/Runner/Release.entitlements
  app/macos/Runner/RunnerDebug.entitlements
  app/pubspec.lock
  app/pubspec.yaml
  app/run.sh
Labels: changelog: added

#250 Update README.md - git and find parameters changed
  supabase/hosting/README.md
Labels: changelog: changed

#253 Simplify Self Hosting of Edge Functions
  supabase/functions/main/index.ts
  supabase/hosting/.gitignore
  supabase/hosting/README.md
  supabase/hosting/volumes/functions/main/index.ts
Labels: changelog: changed
